version: 0.2

phases:
  #install:
  #  runtime-versions:
  #    java: corretto11
  pre_build:
    commands:
      - aws --version
      - which aws
      - pip3 install --upgrade --user awscli
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - chmod +x deploy-cfn.sh
      - ./deploy-cfn.sh 
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar